"""Generate the ICLR supplementary appendix (LaTeX + Markdown) from the results.

Full per-method tables that do not fit in the main paper: all metrics, all
seeds aggregated, with standard deviations and paired statistics.
"""
from __future__ import annotations
import json, math, os
from collections import defaultdict

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "supplementary")
T_CRIT_9 = 2.262
SUITES = ["grid_noflow", "measured", "grid"]
METRICS = [("energy_score", "ES"), ("crps", "CRPS"), ("variogram_score", "VS"),
           ("sliced_w1", "SW$_1$"), ("mmd2", "MMD$^2$"), ("marginal_w1", "MW$_1$"),
           ("acf_err", "ACF err"), ("ramp_w1", "Ramp W$_1$"), ("psd_err", "PSD err"),
           ("reliability_index", "RI"), ("cov90", "cov$_{90}$"), ("cov50", "cov$_{50}$"),
           ("eq_max", r"$\|Ax-b\|_\infty$")]


def load(n):
    p = os.path.join(RES, n)
    return [json.loads(l) for l in open(p) if l.strip()] if os.path.exists(p) else []


def ms(v):
    v = [x for x in v if x is not None and np.isfinite(x)]
    if not v:
        return float("nan"), float("nan")
    return float(np.mean(v)), (float(np.std(v, ddof=1)) if len(v) > 1 else 0.0)


def num(x, sig=3):
    if x is None or not np.isfinite(x):
        return "--"
    ax = abs(x)
    if ax != 0 and (ax < 1e-3 or ax >= 1e4):
        return f"\\num{{{x:.{sig-1}e}}}"
    out = f"{x:.{sig}g}"
    return f"\\num{{{out}}}" if "e" in out else out


def paired(rows, a, b, key="energy_score"):
    by = defaultdict(dict)
    for r in rows:
        by[r["method"]][r["seed"]] = r
    seeds = sorted(set(by.get(a, {})) & set(by.get(b, {})))
    if len(seeds) < 2:
        return None
    d = np.array([by[a][s][key] - by[b][s][key] for s in seeds], float)
    base = np.mean([by[b][s][key] for s in seeds])
    return 100 * d.mean() / base, d.mean() / (d.std(ddof=1) / math.sqrt(len(d))), len(d)


def main():
    os.makedirs(OUT, exist_ok=True)
    meta = json.load(open(os.path.join(RES, "suite_meta.json")))
    mains = {s: load(f"main_{s}.jsonl") for s in SUITES}
    L = []
    w = L.append
    w(r"% Supplementary appendix -- generated by scripts/make_appendix.py.")
    w(r"% Requires siunitx (\num) and booktabs.")
    w(r"\section{Full result tables}")
    w(r"\label{app:full}")
    w("")
    w("Every table in this appendix is generated directly from the run files by "
      r"\texttt{scripts/make\_appendix.py}; no value is transcribed by hand. "
      "Entries are mean $\\pm$ standard deviation across seeds.")
    w("")

    # ---- geometry
    w(r"\subsection{Benchmark geometry}")
    w(r"\begin{table}[h]\centering\small")
    w(r"\begin{tabular}{lrrrrr}\toprule")
    w(r"suite & days & $D$/hour & constraints/hour & dof/hour & codim $r/D$ \\\midrule")
    for s in SUITES:
        m = meta[s]
        w(f"\\texttt{{{s.replace('_',chr(92)+'_')}}} & {m['n_days']} & {m['D']} & "
          f"{m['affine_rank_per_hour']} & {m['affine_dof_per_hour']} & "
          f"{m['codim_frac']:.3f} \\\\")
    w(r"\bottomrule\end{tabular}")
    w(r"\caption{The three affine suites. \texttt{grid\_noflow} and \texttt{grid} are "
      r"the same 118-bus system and the same measured injections; \texttt{grid} "
      r"additionally carries the 186 line flows, which $A$ determines exactly.}")
    w(r"\end{table}")
    w("")

    # ---- per-suite full metric tables
    for s in SUITES:
        rows = mains[s]
        if not rows:
            continue
        by = defaultdict(list)
        for r in rows:
            by[r["method"]].append(r)
        nseed = len({r["seed"] for r in rows})
        order = sorted(by, key=lambda k: ms([r["energy_score"] for r in by[k]])[0])
        for half, keys in [("a", METRICS[:7]), ("b", METRICS[7:])]:
            w(r"\begin{table}[h]\centering\footnotesize")
            w(r"\begin{tabular}{l" + "r" * len(keys) + r"}\toprule")
            w("method & " + " & ".join(k[1] for k in keys) + r" \\\midrule")
            for mth in order:
                cells = []
                for key, _ in keys:
                    mu, sd = ms([r.get(key) for r in by[mth]])
                    cells.append(num(mu))
                nm = mth.replace("_", r"\_").replace("(ours)", r"\textbf{(ours)}")
                w(f"{nm} & " + " & ".join(cells) + r" \\")
            w(r"\bottomrule\end{tabular}")
            sn = s.replace("_", r"\_")
            w(f"\\caption{{Suite \\texttt{{{sn}}}, part {half} of 2. "
              f"{len(by)} methods, {nseed} seeds. Lower is better for every column "
              f"except the coverage columns, whose targets are 0.9 and 0.5.}}")
            w(r"\end{table}")
            w("")

    # ---- paired table
    w(r"\subsection{Paired comparisons against unconstrained flow matching}")
    w(r"\begin{table}[h]\centering\small")
    w(r"\begin{tabular}{llrrrl}\toprule")
    w(r"suite & method & codim & $\Delta$ES & paired $t$ & verdict \\\midrule")
    for s in SUITES:
        for mth in ["HFM (ours)", "FM+reduced", "FM+DC3", "FM+PCFM", "FM+posthoc"]:
            r = paired(mains[s], mth, "FM")
            if not r:
                continue
            pct, t, n = r
            v = ("better" if pct < 0 else "worse") if abs(t) > T_CRIT_9 else "n.s."
            sn = s.replace("_", r"\_")
            nm = mth.replace("_", r"\_")
            w(f"\\texttt{{{sn}}} & {nm} & {meta[s]['codim_frac']:.3f} & "
              f"{pct:+.2f}\\% & {t:+.2f} & {v} \\\\")
        w(r"\midrule")
    w(r"\bottomrule\end{tabular}")
    w(r"\caption{Paired by seed on the identical backbone, budget and data. "
      r"A positive $\Delta$ES means the constrained route scores worse. "
      r"$|t|>2.262$ is significant at the 5\% level on 9 degrees of freedom.}")
    w(r"\end{table}")
    w("")

    # ---- downstream
    down = load("downstream.jsonl")
    if down:
        reg = defaultdict(list)
        for r in down:
            if r.get("regret_pct") is not None:
                reg[r["method"]].append(r["regret_pct"])
        w(r"\subsection{Downstream: two-stage stochastic unit commitment}")
        w(r"\begin{table}[h]\centering\footnotesize")
        w(r"\begin{tabular}{lrrrr}\toprule")
        w(r"method & regret \% & $\pm$ & shed (MWh) & days shed \\\midrule")
        for mth in sorted(reg, key=lambda k: np.mean(reg[k])):
            v = [r for r in down if r["method"] == mth]
            mu, sd = ms(reg[mth])
            sh, _ = ms([r["mean_shed_mwh"] for r in v])
            fr, _ = ms([r["frac_days_shed"] for r in v])
            nm = mth.replace("_", r"\_").replace("[det-mean]", r"[det.\ mean]")
            w(f"{nm} & {mu:.2f} & {sd:.2f} & {sh:.1f} & {fr:.3f} \\\\")
        w(r"\bottomrule\end{tabular}")
        nseeds = max(len(v) for v in reg.values())
        w(f"\\caption{{Cost regret against perfect foresight, {nseeds} seeds. "
          r"\texttt{[det-mean]} rows commit on the ensemble mean rather than the "
          r"scenario set, and are included to show the harness discriminates.}")
        w(r"\end{table}")
        w("")

    # ---- transfer, efficiency, AC
    tr = load("transfer.jsonl")
    if tr:
        by = defaultdict(list)
        for r in tr:
            by[(r["method"], r["mode"])].append(r)
        w(r"\subsection{Zero-shot N-1 topology transfer}")
        w(r"\begin{table}[h]\centering\small")
        w(r"\begin{tabular}{llrrr}\toprule")
        w(r"method & chart & $\|A'x-b'\|_\infty$ & ES & VS \\\midrule")
        for k in sorted(by, key=lambda k: (k[1], ms([r["energy_score"] for r in by[k]])[0])):
            v = by[k]
            nm = k[0].replace("_", r"\_")
            w(f"{nm} & {k[1]} & {num(ms([r['eq_max'] for r in v])[0])} & "
              f"{num(ms([r['energy_score'] for r in v])[0], 4)} & "
              f"{num(ms([r['variogram_score'] for r in v])[0], 4)} \\\\")
        w(r"\bottomrule\end{tabular}")
        w(r"\caption{Eight single-branch outages. \texttt{swapped} rebuilds the "
          r"projector or chart from the contingency PTDF; \texttt{stale} does not.}")
        w(r"\end{table}")
        w("")

    eff = load("efficiency.jsonl")
    if eff:
        w(r"\subsection{Accuracy--NFE frontier}")
        w(r"\begin{table}[h]\centering\footnotesize")
        w(r"\begin{tabular}{llrrrr}\toprule")
        w(r"method & solver & NFE & ES & $\|Ax-b\|_\infty$ & FLOPs/scenario \\\midrule")
        for r in sorted(eff, key=lambda r: (r["method"], r["solver"], r["nfe"])):
            nm = r["method"].replace("_", r"\_")
            w(f"{nm} & {r['solver']} & {r['nfe']} & {num(r['energy_score'],4)} & "
              f"{num(r['eq_max'])} & {num(r['flops_per_scenario'])} \\\\")
        w(r"\bottomrule\end{tabular}")
        w(r"\caption{Suite \texttt{grid}. NFE and analytic FLOPs are exactly countable "
          r"and hardware-independent. Wall-clock is recorded in the run file but is "
          r"single-seed and was measured under thermal contention; it supports no "
          r"claim in this paper.}")
        w(r"\end{table}")
        w("")

    ac = load("ac.jsonl") + load("ac_retract20.jsonl")
    if ac:
        w(r"\subsection{Nonlinear AC power-flow manifold}")
        w(r"\begin{table}[h]\centering\small")
        w(r"\begin{tabular}{lrrrrr}\toprule")
        w(r"method & retract iters & steps & $|g|_\infty$ & $|g|_{\mathrm{RMSE}}$ & ES \\\midrule")
        for r in ac:
            nm = r["method"].replace("_", r"\_")
            w(f"{nm} & {r.get('retract_iters',3)} & {r['steps']} & "
              f"{num(r['nl_max'])} & {num(r['nl_rmse'])} & {r['energy_score']:.4f} \\\\")
        w(r"\bottomrule\end{tabular}")
        m = meta.get("ac", {})
        w(f"\\caption{{IEEE 57-bus, {m.get('manifold_codim_per_hour','?')} nonlinear "
          f"equations per hour on $D={m.get('D','?')}$. "
          r"\texttt{FM+retract-final} applies one Gauss-Newton retraction after the "
          r"solve; \texttt{Manifold-FM} retracts inside every step.}")
        w(r"\end{table}")
        w("")

    with open(os.path.join(OUT, "appendix_tables.tex"), "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote supplementary/appendix_tables.tex ({len(L)} lines)")


if __name__ == "__main__":
    main()
